[deploy]
bucket = 'cfn-artifacts-adikaifeanyi'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cloudtropper.site'
EnvBackendUrl = 'https://api.cloudtropper.site'
DDBMessageTable = 'CrdDdb-DynamoDBTable-X59DMGWQI1OX'