[deploy]
bucket = 'cfn-artifacts-adikaifeanyi'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'afumchris/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cloudtropper-artifacts"